server:
  port: 9527
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proIncorruptibleAiliance
    username: root
    password: liuze1998526
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    servlet:
      multipart:
        maxFileSize: 50MB  #单位必须大写MB或不写(即为B)
        maxRequestSize: 100MB
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  type-aliases-package: com.onlineplatform.proincorruptiblealliance.entity
  configuration:
    map-underscore-to-camel-case: true

#  mapper-locations: classpath:mapper/*.xml
#  #  逆向工程配置,完成逆向工程后，请将以下 ↓ 代码段注释或删除
#  config-location: classpath:generatorConfig.xml
#配置Mysql连接